# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environments',
            fields=[
                ('eid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('env_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('ename', models.CharField(max_length=200)),
                ('f_name', models.CharField(max_length=200)),
                ('f_dis', models.CharField(max_length=200)),
                ('f_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FarmsRoles',
            fields=[
                ('ename', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('rid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('r_name', models.CharField(max_length=200)),
                ('r_platform', models.CharField(max_length=200)),
                ('r_category', models.CharField(max_length=200)),
                ('r_cloudlocation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('ename', models.CharField(max_length=200)),
                ('fname', models.CharField(max_length=200)),
                ('frname', models.CharField(max_length=200)),
                ('sid', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('sip', models.CharField(max_length=200)),
                ('uptime', models.CharField(max_length=200)),
                ('s_name', models.CharField(max_length=200)),
                ('s_status', models.CharField(max_length=200)),
                ('s_alias', models.CharField(max_length=200)),
            ],
        ),
    ]
