# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='f_dis',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
