# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160826_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='f_status',
            field=models.BooleanField(),
        ),
    ]
