# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160826_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='f_status',
            field=models.CharField(max_length=20),
        ),
    ]
