# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20160826_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farmsroles',
            old_name='r_category',
            new_name='r_alias',
        ),
        migrations.RemoveField(
            model_name='farmsroles',
            name='r_cloudlocation',
        ),
        migrations.RemoveField(
            model_name='farmsroles',
            name='r_platform',
        ),
        migrations.AddField(
            model_name='farmsroles',
            name='r_max',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='farmsroles',
            name='r_min',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
