# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-09 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20160909_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='ename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='f_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
