# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-15 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20160909_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environments',
            name='eid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farms',
            name='ename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farms',
            name='f_dis',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farms',
            name='f_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farms',
            name='fid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='rid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='server',
            name='sid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
