# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 11:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20160915_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='s_alias',
            new_name='s_type',
        ),
        migrations.RemoveField(
            model_name='server',
            name='s_name',
        ),
    ]
