# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20160916_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='ename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farms',
            name='f_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='ename',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='fname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='r_alias',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='r_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
