# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20160916_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servers',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('ename', models.CharField(max_length=200)),
                ('fname', models.CharField(blank=True, max_length=200, null=True)),
                ('frname', models.CharField(blank=True, max_length=200, null=True)),
                ('sip', models.CharField(max_length=200)),
                ('s_status', models.CharField(max_length=200)),
                ('uptime', models.CharField(max_length=200)),
                ('s_type', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.AlterField(
            model_name='farmsroles',
            name='ename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
