# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-16 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20160916_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='s_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='sip',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='servers',
            name='uptime',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
