# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 16:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20160916_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='sid',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
