# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-21 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20161221_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='sid',
            field=models.CharField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
