# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-22 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20161221_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='GEServers',
            fields=[
                ('sid', models.AutoField(primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=200)),
                ('ename', models.CharField(max_length=200)),
                ('hostname', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
            ],
        ),
    ]
